"""add dispute system

Revision ID: 42098c496863
Revises: 8692a810a7b1
Create Date: 2026-08-17 11:58:24.000000

Whole-agreement disputes, resolved by a platform admin.

Hand-written rather than autogenerated for three reasons:
  * the partial unique index carries a WHERE clause, which autogenerate does
    not emit (same reason 223902e70386 is hand-written);
  * `dispute` must be created before asset.dispute_id's FK, whereas
    autogenerate orders table operations alphabetically;
  * user.is_admin needs a server_default, which autogenerate omits — without
    it the ALTER fails on any non-empty user table.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42098c496863"
down_revision: Union[str, Sequence[str], None] = "8692a810a7b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Platform staff flag. server_default is required: the column is NOT NULL
    # and the user table already has rows.
    op.add_column(
        "user",
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )

    # Created before the asset.dispute_id foreign key below.
    op.create_table(
        "dispute",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agreement_id", sa.String(), nullable=False),
        sa.Column("raised_by_user_id", sa.String(), nullable=False),
        sa.Column("against_user_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(32), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("agreement_status_before", sa.String(), nullable=False),
        sa.Column("resolution_outcome", sa.String(32), nullable=True),
        sa.Column("resolution_notes", sa.String(), nullable=True),
        sa.Column("resolved_by_user_id", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agreement_id"], ["agreement.id"]),
        sa.ForeignKeyConstraint(["raised_by_user_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["against_user_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["resolved_by_user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_dispute_agreement_id", "dispute", ["agreement_id"])
    op.create_index("ix_dispute_status", "dispute", ["status"])
    op.create_index("ix_dispute_raised_by_user_id", "dispute", ["raised_by_user_id"])
    op.create_index("ix_dispute_against_user_id", "dispute", ["against_user_id"])

    # At most one live dispute per agreement. Partial unique index — not
    # expressible through autogenerate. This is the race-proof floor under the
    # service-level 409 guard.
    op.execute(
        """
        CREATE UNIQUE INDEX ux_dispute_one_active_per_agreement
        ON dispute (agreement_id)
        WHERE status IN ('open', 'under_review')
        """
    )

    # Dispute evidence reuses the existing asset/asset_file upload path.
    op.add_column("asset", sa.Column("dispute_id", sa.String(), nullable=True))
    op.create_foreign_key(
        "fk_asset_dispute_id", "asset", "dispute", ["dispute_id"], ["id"]
    )
    op.create_index("ix_asset_dispute_id", "asset", ["dispute_id"])
    # An asset belongs to a condition (a deliverable) or a dispute (evidence),
    # never both and never neither.
    op.create_check_constraint(
        "ck_asset_single_parent",
        "asset",
        "(condition_id IS NOT NULL AND dispute_id IS NULL) "
        "OR (condition_id IS NULL AND dispute_id IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_asset_single_parent", "asset", type_="check")
    op.drop_index("ix_asset_dispute_id", table_name="asset")
    op.drop_constraint("fk_asset_dispute_id", "asset", type_="foreignkey")
    op.drop_column("asset", "dispute_id")

    op.execute("DROP INDEX IF EXISTS ux_dispute_one_active_per_agreement")
    op.drop_index("ix_dispute_against_user_id", table_name="dispute")
    op.drop_index("ix_dispute_raised_by_user_id", table_name="dispute")
    op.drop_index("ix_dispute_status", table_name="dispute")
    op.drop_index("ix_dispute_agreement_id", table_name="dispute")
    op.drop_table("dispute")

    op.drop_column("user", "is_admin")
