"""initial_tables

Revision ID: c4ab132bbc2c
Revises:
Create Date: 2026-03-13 11:57:43.374445

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4ab132bbc2c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreement",
        sa.Column("agreement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("agreement_id"),
    )
    op.create_table(
        "asset_file",
        sa.Column("file_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "profile_picture_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("active", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_phone_number"), "user", ["phone_number"], unique=False
    )
    op.create_table(
        "agreement_participant",
        sa.Column("participant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agreement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agreement_id"],
            ["agreement.agreement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("participant_id"),
    )
    op.create_table(
        "invitation",
        sa.Column("invitation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agreement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invited_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agreement_id"],
            ["agreement.agreement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("invitation_id"),
    )
    op.create_table(
        "condition",
        sa.Column("condition_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agreement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("participant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invitation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "required_from_participant_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("rejected_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agreement_id"],
            ["agreement.agreement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["invitation.invitation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["agreement_participant.participant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["required_from_participant_id"],
            ["agreement_participant.participant_id"],
        ),
        sa.PrimaryKeyConstraint("condition_id"),
    )
    op.create_table(
        "transaction",
        sa.Column("transaction_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agreement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("participant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("condition_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agreement_id"],
            ["agreement.agreement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["agreement_participant.participant_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_table(
        "asset",
        sa.Column("asset_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("condition_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uploaded_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["condition.condition_id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["asset_file.file_id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["agreement_participant.participant_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asset")
    op.drop_table("transaction")
    op.drop_table("condition")
    op.drop_table("invitation")
    op.drop_table("agreement_participant")
    op.drop_index(op.f("ix_user_phone_number"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("asset_file")
    op.drop_table("agreement")
    # ### end Alembic commands ###
